# This workflow will automatically deploy your application to www.evennode.com on push to main branchse

name: Deploy to EvenNode

on:
  push:
    branches: [ main ]

jobs:
  Deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Install SSH key
      uses: shimataro/ssh-key-action@v2
      with:
        key:  MIICXQIBAAKBgQCVmoBlogzK5lvJiWumL2udZbiEHaEMMzt8hqYANe2lppAIbRf6kqgDZ/e2k8Qu/GaJxi3CsIOFPEvLv8zfXrdAiAp39HUYteRk45q9pSonT69zHa52Imjx8G5LS5tfgtp2lqW3QCcXNyicsuac8LOj4sXbqKZksnWPK5CvsaTUzwIDAQABAoGATANDp+Atpc5j5sPXGYpQoJm1phMz5/IEEKKNp9++zwMRfeaIX32ytoBWAcOU09bU9r3mNFzhhon7bRwYKYqDixBl4naY2CgwPU8nrX8BGRsV81552TWjh7B6v6fQvXaAzl1F9C5eST3K8iDEEb0fWYHfRzzVsJA4QoMSn6efiykCQQDvcSBIngaTIbwCo8dp9Gku7MadmCC4W9WICwrypWvBst4+6A+dRMENVVDPfShGuVhpNqR/oP5l35bLlh4tD4rrAkEAn/L0M4WWpvVzLu2P7EQMjwcfoZ7J95CSZOjOCgiV5gYbh11z0TU7EBesY6kH6rmE7sF2fhC+cRzLmRF3E8bcrQJBALorbzqHA/2qIRC8XvRXAOFnYBZwjiBJ5wDb9Sssy1fTx1GKBXn2V1QSnb52RbaXrdJAli5V8vcqnYi1s8i9aPkCQDU4M4TJGD1pQfAFX3PvmHYmmqG+IdlbozosNBImlSm6MoKx141utr4+AkAOx/GT1OVUPcbob1VXjW7a3tIXwukCQQDWZdQubfW1inbXeZbj3Dp0ic19ZJYVYRpFFRgKImXHbE1W2lzXpno1H+/QhpwAVcXM43j4aILboSzOG2ki6e/w 
        known_hosts: " "
    - name: Add git.evennode.com to known_hosts
      run: |
        ssh-keyscan -H git.evennode.com > ~/.ssh/known_hosts
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Deploy to evennode.com
      run: |
        git remote add evennode git@git.evennode.com:1b8cc12dc888f1e3c2a3862833e1b712.git
        git config --global user.email 903054@lcps.org 
        git config --global user.name Louis654
        git push evennode +main
