# This workflow will automatically deploy your application to www.evennode.com on push to main branchs

name: Deploy to EvenNode

on:
  push:
    branches: [ main ]

jobs:
  Deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Install SSH key
      uses: shimataro/ssh-key-action@v2
      with:
        key:  AAAAB3NzaC1yc2EAAAADAQABAAABAQCPQxcWsYjG4f/Cu/MXFsuRVV91lRIdwDdOy5fPoC0PWszPqZqVRzb3bn9iXP8IyKu36NL3ZsQdmobxkj8B9Y1CqUxg+M4B/zOYCOPfZD6Y3e4z6AZerMRqdUbivRcFm+he4eACioZsfAWU8ssWkTQaLjme73/px584yxiTQ4Yzx0QcJGAFOV7ciPMUOlWBAkYuQI6+jJbvcdkhJKSs+TM7R7OxnC5gMmMwCODyijs0V9Z5WG2XU3O3mUjXQvuF9ACJeuvVsCoJnXiWfbJVNZaqKVeta2Xl+lnR61nEoP6iYZ9cbL0OlfXUEdwFeXGLR63Y+J94nHaiNH0aT10pQ8PH  
        known_hosts: " "
    - name: Add git.evennode.com to known_hosts
      run: |
        ssh-keyscan -H git.evennode.com > ~/.ssh/known_hosts
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Deploy to evennode.com
      run: |
        git remote add evennode  git@git.evennode.com:1b8cc12dc888f1e3c2a3862833e1b712.git
        git config --global user.email  903054@lcps.org 
        git config --global user.name  turtles_68ace 
        git push evennode +main
